//! This crate contains useful types and methods for working with metrics in bioyino statsd server and some other
//! metric processing software. Features:
//!
//! * a type for representing typed and timestamped metrics, generic over floating point format
//! * streaming parser of statsd format
//! * metric aggregation routines
//! * working with Graphite-compatible metric naming including basic tags support
//! * schema and functions for sending/receiving metrics in binary Cap'n'Proto format

/// Aggregation routines
pub mod aggregate;
/// Metric values routines
pub mod metric;
/// Metric name routines
pub mod name;
/// Metric parsing routines
pub mod parser;
/// Convenience types
pub mod prelude;

pub use crate::metric::*;
pub use crate::name::MetricName;
pub use crate::prelude::*;

/// An autogenerated module for working with capnp schema
pub mod protocol_capnp {
    include!(concat!(env!("OUT_DIR"), "/schema/protocol_capnp.rs"));
}

/// An autogenerated module for working with capnp schema version 2
pub mod protocol_v2_capnp {
    include!(concat!(env!("OUT_DIR"), "/schema/protocol_v2_capnp.rs"));
}
